language: android
sudo: true # y tho

env:
  global:
    - COMPILE_SDK_VERSION=27 
    - BUILD_TOOLS_VERSION=27.0.3

android:
  components:
    - tools # Update android-sdk (also called android-sdk-tools)
    - platform-tools
    - tools # Write the second time to update to thes newest as described in the document
    - build-tools-${BUILD_TOOLS_VERSION} # For building
    - android-${COMPILE_SDK_VERSION} # For building
    - extra-android-m2repository # Support library

cache:
  directories:
    - spritegenerator/emojidata

# whitelist
branches:
  only:
    - kt-n
    - ps

before_install:
  - chmod +x gradlew
  - chmod +x build.sh
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo add-apt-repository --yes ppa:deadsnakes/ppa
  - sudo apt-get update

script: ./build.sh

install:
  - sdkmanager --list || true # Debug / Observation
  - echo y | sdkmanager "platforms;android-27"
  - avdmanager --list || true  # Debug / Observation
  - sudo apt-get install -y nodejs
  - sudo apt-get install -y python3.6
  - curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6
  
before_deploy:
  - chmod +x scripts/changelog.sh
  - cp app/build/outputs/apk/release/*.apk TelegramXEmojis-$TRAVIS_BUILD_NUMBER.apk

deploy:
  - provider: script
    skip_cleanup: true
    script: "sh scripts/deploy-telegram.sh"
    on:
      branch: kt-n
